#!/bin/sh

rm -f  config.log config.status confdefs.h \
       src/*.o src/*.so src/Makevars src/symbols.rds \
       inst/doc/*.blg inst/doc/*.bbl \
       */*~ *~ 
rm -rf autom4te.cache inst/doc/*/auto

(cd inst/examples/RcppGSLExample;  \
    rm -f  config.log config.status  \
           src/*.o src/*.so src/Makevars \
           */*~ *~ ; \
    rm -rf autom4te.cache)

(cd vignettes && \
    make clean && \
    rm -rf auto unitTests-results/ )

