// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppGSL.h"
#include <Rcpp.h>

using namespace Rcpp;

// gslSetErrorHandlerOff
bool gslSetErrorHandlerOff();
RcppExport SEXP RcppGSL_gslSetErrorHandlerOff() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(gslSetErrorHandlerOff());
    return __result;
END_RCPP
}
// gslResetErrorHandler
bool gslResetErrorHandler();
RcppExport SEXP RcppGSL_gslResetErrorHandler() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(gslResetErrorHandler());
    return __result;
END_RCPP
}
