# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLm_impl <- function(X, y) {
    .Call(`_RcppGSL_fastLm`, X, y)
}

gslSetErrorHandlerOff <- function() {
    .Call(`_RcppGSL_gslSetErrorHandlerOff`)
}

gslResetErrorHandler <- function() {
    .Call(`_RcppGSL_gslResetErrorHandler`)
}

